apiVersion: v2
name: shop
description: The shop microservices application
type: application
version: 0.1.0        # version of the CHART (the packaging)
appVersion: "1.0.0"   # version of the APP inside