global:
  imageRepo: adidr10   # matches DOCKERHUB_USERNAME
  imageTag: v1                           # CI bumps this to the commit SHA

frontend:
  replicas: 1
productsApi:
  replicas: 1
ordersApi:
  replicas: 1
gateway:
  nodePort: 30080
imagePullSecrets: []